# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/is_registered/100
Accept: application/json

###

GET http://127.0.0.1:8000/register/100
Accept: application/json

###

GET http://127.0.0.1:8000/register/100
Accept: application/json

###

GET http://127.0.0.1:8000/debit/100/200
Accept: application/json